/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 rabbit.glb -T 
Files: rabbit.glb [4.8MB] > C:\Users\USER\Desktop\hoplite-1\hoplite52\public\models\rabbit-transformed.glb [616.08KB] (87%)
Author: bauerband (https://sketchfab.com/bauerband)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/robo-rabbit-v3-073b02715024472a8e1f5bb2627d190f
Title: Robo Rabbit V3
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Rabbit(props) {
  const { nodes, materials } = useGLTF('/models/rabbit-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.lambert2} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/rabbit-transformed.glb')
