/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 road.glb -T 
Files: road.glb [14.55MB] > C:\Users\USER\Desktop\hoplite-1\hoplite52\public\models\road-transformed.glb [867.6KB] (94%)
Author: Dzhusi one (https://sketchfab.com/dzhusione)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/desert-road-48b076dadec243cbb7b7d7d37de097d3
Title: Desert road
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Road(props) {
  const { nodes, materials } = useGLTF('/models/road-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.body_body_0.geometry} material={materials.body} position={[-0.433, 2.849, 0.007]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.terrain_terrain_0.geometry} material={materials.terrain} position={[-0.425, 1.093, 0.037]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.sky_sky_0.geometry} material={materials.material} position={[-0.433, 2.849, 0.007]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.glass_glass_0.geometry} material={materials.glass} position={[-0.433, 2.849, 0.007]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.body001outline_body001outline_0.geometry} material={materials.body001outline} position={[-0.433, 2.849, 0.007]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/models/road-transformed.glb')
